# Generated by Django 4.0.4 on 2022-05-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_category_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='wepukhulu', max_length=80),
        ),
    ]
