# Generated by Django 4.0.4 on 2022-05-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['uploaded_at']},
        ),
    ]
